name: Node.js CI
on: 
  pull_request:
    branches: [ develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 21
      uses: actions/setup-node@v2
      with:
        node-version: 21.x
      - name: Install dependencies
      run: npm install
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
